[workspace]
members = [
  "01_concatenate_strings",
  "02_simple_calculator",
  "03_basic_banking_system",
  "04_custom_filtering_function",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
